chore: update pre-commit git hook

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -1,5 +1,19 @@
 #!/bin/sh
 
+if [ -d "/Applications/Android Studio.app" ]; then
+    # Default Android Studio install location
+    ANDROID_STUDIO_PATH="/Applications/Android Studio.app"
+elif [ -d "$HOME/Applications/Android Studio.app" ]; then
+    # Jetbrains Android Studio install location
+    ANDROID_STUDIO_PATH="$HOME/Applications/Android Studio.app"
+else
+   echo "Unable to find the Android Studio application"
+   exit 1
+fi
+
+JAVA_HOME=$ANDROID_STUDIO_PATH/Contents/jbr/Contents/Home
+export JAVA_HOME
+
 ######## KTLINT-GRADLE HOOK START ########
 
 CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $NF ~ /\.kts?$/ { print $NF }')"
@@ -12,36 +26,17 @@ fi;
 echo "Running ktlint over these files:"
 echo "$CHANGED_FILES"
 
-diff=.git/unstaged-ktlint-git-hook.diff
-git diff --color=never > $diff
-if [ -s $diff ]; then
-  git apply -R $diff
-fi
-
 ./gradlew --quiet ktlintCheck -PinternalKtlintGitFilter="$CHANGED_FILES"
-gradle_command_exit_code=$?
+EXIT_CODE=$?
 
 echo "Completed ktlint run."
 
-echo "$CHANGED_FILES" | while read -r file; do
-    if [ -f $file ]; then
-        git add $file
-    fi
-done
-
-
-if [ -s $diff ]; then
-  git apply --ignore-whitespace $diff
+if [ $EXIT_CODE -ne 0 ]; then
+  exit $EXIT_CODE
 fi
-rm $diff
-unset diff
 
 echo "Completed ktlint hook."
 ######## KTLINT-GRADLE HOOK END ########
-
-if [ $gradle_command_exit_code -ne 0 ]; then
-  exit $gradle_command_exit_code
-fi
 
 ######## DETEKT HOOK START ########
 
